version: '3'
services:
    quote:
        image: 'qq-quote-generator:1.7'
        container_name: qq-quote
        ports:
            - '5002:5000'
        restart: unless-stopped
networks:
  default:
    external: true
    name: app_default
